spring:
  application:
    name: newsrecommendation
  datasource:
    url: jdbc:postgresql://localhost:5432/articles_app
    username: postgres_user
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  tomcat:
    threads:
      max: 200
      min: 10
logging:
  level:
    com.example.newsrecommendation.controller: DEBUG
    com.example.newsrecommendation.service: DEBUG
    com.example.newsrecommendation.repository: DEBUG
    com.example.newsrecommendation.security: DEBUG
    com.example.newsrecommendation.aspect: DEBUG
    org.flywaydb: DEBUG
openapi: 3.0.1
management:
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: "*"
        exclude: shutdown
  resilience4j.ratelimiter:
    instances:
      apiRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 5s
        timeoutDuration: 0
  resilience4j.circuitbreaker:
    instances:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half=open-state: 3
      sliding-window-type: count_based
      sliding-window-size: 10

