spring:
  application:
    name: newsrecommendation
server:
  tomcat:
    threads:
      max: 200
      min: 10
logging:
  level:
    com.example.newsrecommendation.controller: DEBUG
    com.example.newsrecommendation.service: DEBUG
    com.example.newsrecommendation.repository: DEBUG
    com.example.newsrecommendation.security: DEBUG
    com.example.newsrecommendation.aspect: DEBUG
openapi: 3.0.1
management:
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: "*"
        exclude: shutdown
  resilience4j.ratelimiter:
    instances:
      apiRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 5s
        timeoutDuration: 0
  resilience4j.circuitbreaker:
    instances:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half=open-state: 3
      sliding-window-type: count_based
      sliding-window-size: 10

